### ISSUE TITLE
[SPARQL Stories] Making the Map view full screen does not work

### ISSUE THREAD

**Issue by wouterbeek** [OpenTriply/YASGUI#96]
The map can be made full screen, but its height is static.  For one map, it may be possible to do something like the following:

```css
html,
body,
.container-fluid,
.container-fluid .main,
.container-fluid .main .row,
.container-fluid .main .row .col,
#mapid {
  padding: 0;
  margin: 0;
  height: 100%;
  width: 100%;
}
```
